version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  fastapi:
    build:
      context: .
    container_name: ecommerce-api
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: ecommerce_user
      DB_PASSWORD: ecommerce_pass
      DB_NAME: ecommerce
    ports:
      - "8000:8000"
    volumes:
      - ./ecomm:/ecomm

volumes:
  db_data:
